
-- =======================================
-- CREACIÓN DE TABLAS CON RELACIONES DIRECTAS
-- =======================================

-- ===== DEPARTAMENTO =====
CREATE TABLE P2_DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER PRIMARY KEY,
    NOMBRE          VARCHAR2(100) NOT NULL,
    CODIGO          VARCHAR2(10) UNIQUE
);

-- ===== MUNICIPIO =====
CREATE TABLE P2_MUNICIPIO (
    ID_MUNICIPIO NUMBER PRIMARY KEY,
    DEPARTAMENTO_ID_DEPARTAMENTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CODIGO VARCHAR2(10),
    CONSTRAINT FK_MUNICIPIO_DEP FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES P2_DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- ===== CENTRO =====
CREATE TABLE P2_CENTRO (
    ID_CENTRO NUMBER PRIMARY KEY,
    NOMBRE    VARCHAR2(100) NOT NULL,
    MUNICIPIO_ID_MUNICIPIO NUMBER,
    CONSTRAINT FK_CENTRO_MUNICIPIO FOREIGN KEY (MUNICIPIO_ID_MUNICIPIO)
        REFERENCES P2_MUNICIPIO(ID_MUNICIPIO)
);

-- ===== ESCUELA =====
CREATE TABLE P2_ESCUELA (
    ID_ESCUELA NUMBER PRIMARY KEY,
    NOMBRE     VARCHAR2(150) NOT NULL,
    DIRECCION  VARCHAR2(200),
    ACUERDO    VARCHAR2(50)
);

-- ===== UBICACION (relación N:M entre ESCUELA y CENTRO) =====
CREATE TABLE P2_UBICACION (
    ESCUELA_ID_ESCUELA NUMBER NOT NULL,
    CENTRO_ID_CENTRO   NUMBER NOT NULL,
    CONSTRAINT PK_UBICACION PRIMARY KEY (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO),
    CONSTRAINT FK_UBICACION_ESCUELA FOREIGN KEY (ESCUELA_ID_ESCUELA)
        REFERENCES P2_ESCUELA(ID_ESCUELA),
    CONSTRAINT FK_UBICACION_CENTRO FOREIGN KEY (CENTRO_ID_CENTRO)
        REFERENCES P2_CENTRO(ID_CENTRO)
);

-- ===== REGISTRO =====
CREATE TABLE P2_REGISTRO (
    ID_REGISTRO NUMBER PRIMARY KEY,
    UBICACION_ESCUELA_ID_ESCUELA NUMBER NOT NULL,
    UBICACION_CENTRO_ID_CENTRO   NUMBER NOT NULL,
    MUNICIPIO_ID_MUNICIPIO       NUMBER NOT NULL,
    MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO NUMBER NOT NULL,
    CORRELATIVO_ID_CORRELATIVO NUMBER,
    FECHA DATE,
    TIPO_TRAMITE   VARCHAR2(50),
    TIPO_LICENCIA  VARCHAR2(5),
    NOMBRE_COMPLETO VARCHAR2(150),
    GENERO CHAR(1),
    CONSTRAINT FK_REGISTRO_UBICACION FOREIGN KEY (UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO)
        REFERENCES P2_UBICACION(ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO),
    CONSTRAINT FK_REGISTRO_MUNICIPIO FOREIGN KEY (MUNICIPIO_ID_MUNICIPIO)
        REFERENCES P2_MUNICIPIO(ID_MUNICIPIO)
);

-- ===== CORRELATIVO =====
CREATE TABLE P2_CORRELATIVO (
    ID_CORRELATIVO NUMBER PRIMARY KEY,
    FECHA DATE,
    NO_EXAMEN NUMBER,
    REGISTRO_ID_REGISTRO NUMBER NOT NULL,
    CONSTRAINT FK_CORRELATIVO_REGISTRO FOREIGN KEY (REGISTRO_ID_REGISTRO)
        REFERENCES P2_REGISTRO(ID_REGISTRO)
);

-- ===== EXAMEN =====
CREATE TABLE P2_EXAMEN (
    ID_EXAMEN NUMBER PRIMARY KEY,
    REGISTRO_ID_REGISTRO NUMBER NOT NULL,
    CORRELATIVO_ID_CORRELATIVO NUMBER NOT NULL,
    CONSTRAINT FK_EXAMEN_REGISTRO FOREIGN KEY (REGISTRO_ID_REGISTRO)
        REFERENCES P2_REGISTRO(ID_REGISTRO),
    CONSTRAINT FK_EXAMEN_CORRELATIVO FOREIGN KEY (CORRELATIVO_ID_CORRELATIVO)
        REFERENCES P2_CORRELATIVO(ID_CORRELATIVO)
);

-- ===== PREGUNTAS TEÓRICAS =====
CREATE TABLE P2_PREGUNTAS (
    ID_PREGUNTA NUMBER PRIMARY KEY,
    PREGUNTA_TEXTO VARCHAR2(500) NOT NULL,
    RESPUESTA NUMBER,
    RES1 VARCHAR2(200),
    RES2 VARCHAR2(200),
    RES3 VARCHAR2(200),
    RES4 VARCHAR2(200),
    EXAMEN_ID_EXAMEN NUMBER,
    CONSTRAINT FK_PREGUNTA_EXAMEN FOREIGN KEY (EXAMEN_ID_EXAMEN)
        REFERENCES P2_EXAMEN(ID_EXAMEN)
);

-- ===== PREGUNTAS PRÁCTICAS =====
CREATE TABLE P2_PREGUNTAS_PRACTICO (
    ID_PREGUNTA_PRACTICO NUMBER PRIMARY KEY,
    PREGUNTA_TEXTO VARCHAR2(500) NOT NULL,
    PUNTEO NUMBER,
    EXAMEN_ID_EXAMEN NUMBER,
    CONSTRAINT FK_PREG_PRACTICO_EXAMEN FOREIGN KEY (EXAMEN_ID_EXAMEN)
        REFERENCES P2_EXAMEN(ID_EXAMEN)
);

-- ===== RESPUESTAS TEÓRICAS DE USUARIO =====
CREATE TABLE P2_RESPUESTA_USUARIO (
    ID_RESPUESTA_USUARIO NUMBER PRIMARY KEY,
    PREGUNTA_ID_PREGUNTA NUMBER NOT NULL,
    EXAMEN_ID_EXAMEN NUMBER NOT NULL,
    RESPUESTA NUMBER,
    CONSTRAINT FK_RESPUESTA_PREG FOREIGN KEY (PREGUNTA_ID_PREGUNTA)
        REFERENCES P2_PREGUNTAS(ID_PREGUNTA),
    CONSTRAINT FK_RESPUESTA_EXAMEN FOREIGN KEY (EXAMEN_ID_EXAMEN)
        REFERENCES P2_EXAMEN(ID_EXAMEN)
);

-- ===== RESPUESTAS PRÁCTICAS DE USUARIO =====
CREATE TABLE P2_RESPUESTA_PRACTICO_USUARIO (
    ID_RESPUESTA_PRACTICO NUMBER PRIMARY KEY,
    PREGUNTA_PRACTICO_ID_PREGUNTA_PRACTICO NUMBER NOT NULL,
    EXAMEN_ID_EXAMEN NUMBER NOT NULL,
    NOTA NUMBER,
    CONSTRAINT FK_RPU_PREG FOREIGN KEY (PREGUNTA_PRACTICO_ID_PREGUNTA_PRACTICO)
        REFERENCES P2_PREGUNTAS_PRACTICO(ID_PREGUNTA_PRACTICO),
    CONSTRAINT FK_RPU_EXAMEN FOREIGN KEY (EXAMEN_ID_EXAMEN)
        REFERENCES P2_EXAMEN(ID_EXAMEN)
);

-- =======================================
-- AÑADIR FOREIGN KEY FALTANTE PARA DEPENDENCIA CIRCULAR
-- =======================================

ALTER TABLE P2_REGISTRO ADD CONSTRAINT FK_REGISTRO_CORRELATIVO FOREIGN KEY (CORRELATIVO_ID_CORRELATIVO)
    REFERENCES P2_CORRELATIVO(ID_CORRELATIVO);
